# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: gitee-mirrors
      url-base: https://gitee.com/mirrors
    - name: canpool
      url-base: https://gitee.com/icanpool

  projects:
    - name: zephyr
      remote: gitee-mirrors
      revision: v4.3.0
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis
          - cmsis_6    # required by the ARM port
          - hal_nordic # required by the custom_plank board (Nordic based)
          - hal_stm32  # required by the nucleo_f302r8 board (STM32 based)
          - hal_ti
          - hal_espressif
          - fatfs
          - open-amp
          - libmetal
          - lvgl
    - name: pony_thirdparty_quickjs
      remote: canpool
      revision: master
      path: modules/lib/quickjs
    - name: pony_thirdparty_jerryscript
      remote: canpool
      revision: master
      path: modules/lib/jerryscript
    - name: lv_advanced
      remote: canpool
      revision: master
      path: modules/lib/gui/lv_advanced
